<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Book;


/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{

    public function getList()
    {
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.dateRead', 'DESC')
            ->getQuery();

        $query->useResultCache(true, 86400,'book_get_list');

        return $query->getResult();
    }


}
