fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_book_cover:
    path: /upload/images/{subdir}/{image}
_book_file:
    path: /upload/files/{subdir}/{name}

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

