services:
    # These are the Twig extensions that create new filters and functions for
    # using them in the templates
    app.twig.app_extension:
        public:    false
        class:     AppBundle\Twig\AppExtension
        arguments: ['%app_locales%']
        tags:
            - { name: twig.extension }

    app.twig.intl_extension:
        public: false
        class:  Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }


    app.bookentity.subscriber:
        class: AppBundle\EventListener\UtilBooksSubcriber
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    app.image_type_extension:
        class: AppBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }
    app.cache.subscriber:
        class: AppBundle\EventListener\CacheBooksSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
